variable "aws_region" { }
variable "vpc_cidr" { }
variable "publicdmz_subnet_a_cidr" { }
variable "publicdmz_subnet_b_cidr" { }
variable "publicdmz_subnet_c_cidr" { }
variable "publicdmz_subnet_reserved_cidr" { }
variable "private_subnet_a_cidr" { }
variable "private_subnet_b_cidr" { }
variable "private_subnet_c_cidr" { }
variable "private_subnet_reserved_cidr" { }
variable "data_subnet_a_cidr" { }
variable "data_subnet_b_cidr" { }
variable "data_subnet_c_cidr" { }
variable "data_subnet_reserved_cidr" { }
